#!/bin/bash
set -e # Arrêter le script en cas d'erreur

# Construire les images Docker
docker-compose build

# Lancer les conteneurs
docker-compose up -d

curl http://localhost:3000/

# Arrêter les conteneurs
docker-compose down
